import './globals.css'
import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'

// Components
import Navbar from './components/Navbar'

// Fonts are instatiated here and then options are added to configure it
// You can bring in any google font
const rubik = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// Layout components wrap page componets s
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
